import { useState } from 'react';
import { Copy } from 'lucide-react';
import { toast } from 'sonner';
import { ScanReport, TranslatedFinding } from '@/lib/types';
import { generateGitHubFileLink } from '@/lib/githubLinks';

interface ScanResultsProps {
  report?: ScanReport;
  onNewScan: () => void;
  previewMode?: boolean;
}

function generateMarkdownReport(report: ScanReport): string {
  const repoName = report.repoUrl.split('/').slice(-1)[0] || 'repository';
  const date = new Date(report.clonedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const importanceEmoji: Record<string, string> = {
    important: '🔴',
    explore: '🟠',
    note: '🔵',
    fyi: '⚪',
  };

  const formatFindings = (findings: TranslatedFinding[], panelTitle: string): string => {
    if (findings.length === 0) {
      return `✅ No issues found in ${panelTitle}.\n`;
    }
    return findings
      .map((f, idx) => {
        let text = `### ${idx + 1}. ${f.plainLanguage} ${importanceEmoji[f.importance] || ''} [${f.importance.toUpperCase()}]\n\n`;
        if (f.file) {
          const location = f.line ? `${f.file}:${f.line}` : f.file;
          const ghLink = generateGitHubFileLink(report.repoUrl, f.file, f.line);
          text += `**Location:** \`${location}\``;
          if (ghLink) text += ` ([View on GitHub](${ghLink}))`;
          text += '\n\n';
        }
        if (f.context) text += `**Context:** ${f.context}\n\n`;
        if (f.commonApproaches && f.commonApproaches.length > 0) {
          const approaches = Array.isArray(f.commonApproaches) ? f.commonApproaches.join(', ') : f.commonApproaches;
          text += `**Common approaches:** ${approaches}\n\n`;
        }
        if (f.reflection) text += `*Reflection: ${f.reflection}*\n\n`;
        return text;
      })
      .join('---\n\n');
  };

  return `# Lumen Clew Scan Report

**Repository:** ${report.repoUrl}
**Scan Mode:** ${report.scanMode === 'fast' ? 'Fast' : 'Full'}
**Scanned:** ${date}
**Duration:** ${(report.scanDuration / 1000).toFixed(1)}s

---

## Scan Scope

- Files scanned: ${report.scanScope.filesScanned}
- Files skipped: ${report.scanScope.filesSkipped}
- Max file size: ${report.scanScope.maxFileSizeMb}MB

---

## 🔍 Code Quality
*Tool: ESLint*

${formatFindings(report.panels.codeQuality.findings, 'Code Quality')}

---

## 📦 Dependency Health
*Tool: npm audit*

${formatFindings(report.panels.dependencies.findings, 'Dependencies')}

---

## 🗝️ Secrets & Config
*Tool: Pattern Matching*

${formatFindings(report.panels.secrets.findings, 'Secrets')}

---

## ♿ Accessibility
*Tool: AI Scan*

${formatFindings(report.panels.accessibility.findings, 'Accessibility')}

---

*Report generated by Lumen Clew - Awareness, not judgment.*
`;
}

function handleDownloadReport(report: ScanReport) {
  const markdown = generateMarkdownReport(report);
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const repoName = report.repoUrl.split('/').pop() || 'scan';
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `lumen-clew-${repoName}-report.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const PANEL_CONFIG = {
  code_quality: { 
    emoji: '🔍', 
    title: 'Code Quality', 
    tool: 'ESLint',
    reflection: "What's your maintenance timeline?",
    previewContent: [
      'Code style consistency',
      'Potential bugs and errors',
      'Complexity and maintainability',
      'Unused variables and imports',
      'Best practice patterns'
    ]
  },
  dependencies: { 
    emoji: '📦', 
    title: 'Dependency Health', 
    tool: 'npm audit',
    reflection: 'Is this project going to production soon?',
    previewContent: [
      'Known security vulnerabilities',
      'Outdated dependencies',
      'High/critical severity issues',
      'Recommended update paths'
    ]
  },
  secrets: { 
    emoji: '🗝️', 
    title: 'Secrets & Config', 
    tool: 'Patterns',
    reflection: 'Is this repo public or private?',
    previewContent: [
      'Exposed API keys and tokens',
      'Hardcoded credentials',
      '.env file patterns',
      'Sensitive configuration data'
    ]
  },
  accessibility: { 
    emoji: '♿', 
    title: 'Accessibility', 
    tool: 'AI Scan',
    reflection: 'Who are your users?',
    previewContent: [
      'Missing alt text on images',
      'ARIA label issues',
      'Non-semantic HTML elements',
      'Screen reader compatibility'
    ]
  },
};

const IMPORTANCE_COLORS: Record<string, string> = {
  important: 'bg-red-100 text-red-800 border border-red-200',
  explore: 'bg-amber text-navy',
  note: 'bg-blue-100 text-blue-800 border border-blue-200',
  fyi: 'bg-gray-100 text-gray-600 border border-gray-200',
};

function FindingCard({ finding, repoUrl }: { finding: TranslatedFinding; repoUrl?: string }) {
  const [isOpen, setIsOpen] = useState(false);
  const githubLink = repoUrl ? generateGitHubFileLink(repoUrl, finding.file, finding.line) : null;
  
  return (
    <div 
      className="bg-white p-4 border border-navy/10 cursor-pointer hover:border-amber transition hover:shadow-craft hover:-translate-y-1"
      tabIndex={0}
      onClick={() => setIsOpen(!isOpen)}
      onKeyDown={(e) => e.key === 'Enter' && setIsOpen(!isOpen)}
    >
      <div className="flex items-center justify-between">
        <span className="font-semibold text-navy">
          <span className={`transition-transform inline-block ${isOpen ? 'rotate-90' : ''}`}>▸</span> {finding.plainLanguage}
        </span>
        <span className={`text-xs px-2 py-0.5 uppercase font-bold tracking-wider ${IMPORTANCE_COLORS[finding.importance] || IMPORTANCE_COLORS.fyi}`}>
          {finding.importance}
        </span>
      </div>
      {/* Location & GitHub Link */}
      {finding.file && (
        <div className="mt-2 flex items-center flex-wrap gap-3 text-xs">
          <span className="font-mono text-navy/60">
            📍 {finding.file}{finding.line ? `:${finding.line}` : ''}
          </span>
          <button
            onClick={(e) => {
              e.stopPropagation();
              const pathToCopy = finding.file + (finding.line ? `:${finding.line}` : '');
              navigator.clipboard.writeText(pathToCopy).then(() => {
                toast.success('Path copied to clipboard');
              });
            }}
            className="text-navy/40 hover:text-navy/70 transition-colors"
            title="Copy path"
          >
            <Copy size={14} />
          </button>
          {githubLink && (
            <a
              href={githubLink}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
              className="text-amber hover:text-amber/80 font-semibold transition-colors"
            >
              View on GitHub →
            </a>
          )}
        </div>
      )}
      {isOpen && (
        <div className="mt-3 pt-3 border-t border-navy/10 text-sm text-navy/70 space-y-2">
          {finding.context && <p>{finding.context}</p>}
          {finding.commonApproaches && (
            <p><strong>Common approaches:</strong> {finding.commonApproaches}</p>
          )}
          {finding.reflection && (
            <p className="italic text-navy/60 mt-2">💭 {finding.reflection}</p>
          )}
        </div>
      )}
    </div>
  );
}

function PreviewPanel({ panelKey }: { panelKey: string }) {
  const config = PANEL_CONFIG[panelKey as keyof typeof PANEL_CONFIG];
  if (!config) return null;
  
  return (
    <div className="bg-cream p-5 border-3 border-navy/10 shadow-craft hover:shadow-craft-lg hover:-translate-y-1 hover:border-amber transition-all">
      <div className="flex justify-between items-center mb-4 pb-3 border-b border-navy/10">
        <h3 className="font-headline font-bold text-navy text-xl flex items-center gap-2">
          <span className="text-2xl opacity-70" aria-hidden="true">{config.emoji}</span> {config.title}
        </h3>
        <span className="text-xs font-headline uppercase tracking-wide text-navy/60">{config.tool}</span>
      </div>
      
      <div className="bg-white p-4 border border-navy/10">
        <p className="font-bold text-navy mb-3">We'll analyze your code for:</p>
        <ul className="space-y-2">
          {config.previewContent.map((item, idx) => (
            <li key={idx} className="flex items-start gap-2 text-navy/80">
              <span className="text-amber mt-0.5">•</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>
      
      <p className="text-sm italic text-navy/60 mt-5 pt-4 border-t border-dashed border-navy/10">
        Reflection: {config.reflection}
      </p>
    </div>
  );
}

function Panel({ 
  panelKey, 
  findings,
  repoUrl
}: { 
  panelKey: string;
  findings: TranslatedFinding[];
  repoUrl?: string;
}) {
  const config = PANEL_CONFIG[panelKey as keyof typeof PANEL_CONFIG];
  if (!config) return null;
  const hasFindings = findings.length > 0;
  const isAccessibility = panelKey === 'accessibility';
  
  return (
    <div className="bg-cream p-5 border-3 border-navy/10 shadow-craft hover:shadow-craft-lg hover:-translate-y-1 hover:border-amber transition-all">
      <div className="flex justify-between items-center mb-4 pb-3 border-b border-navy/10">
        <h3 className="font-headline font-bold text-navy text-xl flex items-center gap-2">
          <span className="text-2xl opacity-70" aria-hidden="true">{config.emoji}</span> {config.title}
        </h3>
        <span className="text-xs font-headline uppercase tracking-wide text-navy/60">{config.tool}</span>
      </div>
      
      {hasFindings ? (
        <div className="space-y-3">
          <p className="font-bold text-navy mb-3">Issues found: {findings.length}</p>
          {findings.map((finding, idx) => (
            <FindingCard key={idx} finding={finding} repoUrl={repoUrl} />
          ))}
          
          {isAccessibility && (
            <div className="text-sm text-navy/70 bg-amber/10 p-3 border-l-4 border-amber flex gap-2 items-start leading-tight mt-4">
              <span aria-hidden="true">⚠️</span> Note: This is a static analysis. For contrast/keyboard checks, use <a href="https://developer.chrome.com/docs/lighthouse" target="_blank" rel="noopener noreferrer" className="font-bold text-navy hover:underline">Lighthouse</a>.
            </div>
          )}
        </div>
      ) : (
        <div className="bg-white p-6 border-2 border-green-200/50 text-green-900 text-center min-h-[180px] flex flex-col items-center justify-center gap-3">
          <span className="text-5xl opacity-90" aria-hidden="true">✅</span>
          <p className="text-xl font-headline font-bold">No patterns detected.</p>
          <p className="text-sm text-green-800/80 max-w-xs leading-relaxed">
            {panelKey === 'secrets' 
              ? "Great! We didn't find any obvious API keys, tokens, or credentials."
              : "No issues found in this category."}
          </p>
        </div>
      )}
      
      <p className="text-sm italic text-navy/60 mt-5 pt-4 border-t border-dashed border-navy/10">
        Reflection: {config.reflection}
      </p>
    </div>
  );
}

export function ScanResults({ report, onNewScan, previewMode = false }: ScanResultsProps) {
  const scrollToForm = () => {
    document.getElementById('scan-form')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <section id="results-section" className="bg-white pb-12 relative z-10" aria-labelledby="results-heading">
      {/* Navy Banner */}
      <div className="bg-navy py-8 px-8 border-y-4 border-amber mb-12 shadow-craft relative overflow-hidden">
        <div aria-hidden="true" className="absolute inset-0 opacity-10 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcmaWxsPSIjZTZhNjQxIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxjaXJjbGUgY3g9IjMiIGN5PSIzIiByPSIxIi8+PGNpcmNsZSBjeD0iMTMiIGN5PSIxMyIgcj0iMSIvPjwvZz48L3N2Zz4=')]"></div>
        <div className="relative z-10 flex items-center justify-center gap-6">
          <div className="h-2 w-16 bg-amber hidden md:block shadow-sm" aria-hidden="true"></div>
          <h2 id="results-heading" className="text-4xl md:text-5xl text-amber text-center uppercase tracking-tight font-headline font-black shadow-sm">
            Your Scan Results
          </h2>
          <div className="h-2 w-16 bg-amber hidden md:block shadow-sm" aria-hidden="true"></div>
        </div>
      </div>

      {/* Info Callout */}
      <div className="max-w-5xl mx-auto px-6 mb-8">
        <div className="bg-amber/10 border-l-4 border-amber p-5 flex items-start gap-4 shadow-sm hover:shadow-md transition-all">
          <span className="text-3xl" aria-hidden="true">ℹ️</span>
          <div>
            <h3 className="font-headline font-bold text-navy text-lg mb-1">
              Understanding Your Results
            </h3>
            <p className="text-navy/80 text-sm leading-relaxed">
              We translate findings from standard tools. <strong>This is awareness, not direction.</strong> Use your context to make decisions.
            </p>
          </div>
        </div>
      </div>
      
      {/* Results Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-6xl mx-auto px-6 mb-12">
        {previewMode ? (
          <>
            <PreviewPanel panelKey="code_quality" />
            <PreviewPanel panelKey="dependencies" />
            <PreviewPanel panelKey="secrets" />
            <PreviewPanel panelKey="accessibility" />
          </>
        ) : report ? (
          <>
            <Panel panelKey="code_quality" findings={report.panels.codeQuality.findings} repoUrl={report.repoUrl} />
            <Panel panelKey="dependencies" findings={report.panels.dependencies.findings} repoUrl={report.repoUrl} />
            <Panel panelKey="secrets" findings={report.panels.secrets.findings} repoUrl={report.repoUrl} />
            <Panel panelKey="accessibility" findings={report.panels.accessibility.findings} repoUrl={report.repoUrl} />
          </>
        ) : null}
      </div>
      
      {/* Roadmap */}
      <div className="max-w-6xl mx-auto px-6 py-6 bg-sage/10 border-3 border-sage/30">
        <h4 className="mb-4 font-headline font-bold text-navy/50 uppercase tracking-widest text-center">Roadmap: Coming Soon</h4>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-5 opacity-60 grayscale-[30%] cursor-not-allowed text-center" aria-label="Future features list">
          <div className="bg-white p-5 border-3 border-dashed border-sage/40 flex flex-col items-center gap-3 shadow-sm">
            <span className="text-4xl opacity-40 text-sage" aria-hidden="true">🏗️</span>
            <h4 className="font-bold text-navy text-lg">CI/Test Hygiene</h4>
          </div>
          <div className="bg-white p-5 border-3 border-dashed border-sage/40 flex flex-col items-center gap-3 shadow-sm">
            <span className="text-4xl opacity-40 text-sage" aria-hidden="true">🔦</span>
            <h4 className="font-bold text-navy text-lg">Full A11y</h4>
          </div>
          <div className="bg-white p-5 border-3 border-dashed border-sage/40 flex flex-col items-center gap-3 shadow-sm">
            <span className="text-4xl opacity-40 text-sage" aria-hidden="true">⚡</span>
            <h4 className="font-bold text-navy text-lg">Performance</h4>
          </div>
          <div className="bg-white p-5 border-3 border-dashed border-sage/40 flex flex-col items-center gap-3 shadow-sm">
            <span className="text-4xl opacity-40 text-sage" aria-hidden="true">⚖️</span>
            <h4 className="font-bold text-navy text-lg">Bundle Size</h4>
          </div>
        </div>
      </div>
      
      {/* Actions - only show for real results */}
      {!previewMode && (
        <div className="px-12 flex flex-col items-center gap-5 mt-10">
          <button
            onClick={onNewScan}
            className="bg-amber text-navy font-headline text-xl font-bold px-10 py-4 hover:bg-amber/90 transition shadow-craft hover:shadow-craft-lg hover:-translate-y-1 flex items-center gap-3 uppercase tracking-wider border-3 border-amber focus:ring-2 focus:ring-offset-2 focus:ring-navy"
          >
            <span aria-hidden="true">🚀</span> Run Another Scan
          </button>
          <button 
            onClick={() => report && handleDownloadReport(report)}
            className="text-navy/70 font-bold hover:text-amber border-b-2 border-transparent hover:border-amber pb-1 transition-all flex items-center gap-2 font-headline uppercase tracking-wide text-sm focus:text-navy focus:border-navy bg-transparent cursor-pointer"
          >
            <span aria-hidden="true">⬇️</span> Download Report (Markdown)
          </button>
        </div>
      )}
    </section>
  );
}